<?php
    $_product = $this->getProduct();
    $_helper = $this->helper('catalog/output');
?>

<?php $img_arr = explode("x",Mage::getStoreConfig('j2tajaxcheckout/default/j2t_ajax_cart_image_size', Mage::app()->getStore()->getId()));?>

<p class="product-image">
    <?php
        $_img = '<img class="ajax-main-image-area" id="ajax-main-image-area" src="'.$this->helper('catalog/image')->init($_product, 'image')->resize($img_arr[0],$img_arr[1]).'" alt="'.$this->htmlEscape($this->getImageLabel()).'" title="'.$this->htmlEscape($this->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>

