<?php

/**
 * J2T-DESIGN.
 *
 * @category   J2t
 * @package    J2t_Ajaxcheckout
 * @copyright  Copyright (c) 2003-2009 J2T DESIGN. (http://www.j2t-design.com)
 * @license    GPL
 */


/*
$this->numberUpsells()
$this->numberUpsellsPerLine()
*/
?>
<div id="j2t-ajaxupsells" class="j2t-ajaxupsells">
    <?php if($this->canShowUpsells()):?>
        <?php if($collection = $this->getUpsells()):?>
        <?php $items = $collection->getItems();?>
        <?php if(count($items)): ?>
        <span class="j2t-upsells-list-wrapper">
            <h4 class="j2t-upsells-title"><?php echo $this->__('You might also like:');?></h4>

            <table cellspacing="0" class="generic-product-grid catalog-listing j2t-upsells-list" id="j2t-upsell-product-table">
                <tr>
            <?php $items_left = $this->getNumberUpsellsPerLine();?>
            <?php $k=0;foreach ($items as $item):?>
                    <?php if($k >= $this->getNumberUpsells()) break;?>
                    
                    <?php if ($k > 0 && $k%$this->getNumberUpsellsPerLine() == 0):
                        echo '</tr><tr>';
                        $items_left = $this->getNumberUpsellsPerLine();
                    else:
                        $items_left--;
                    endif;?>
                    
                <td class="j2t-upsells-list-item">
                <span class="j2t-product-image"><a href="<?php echo $item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize($this->getImageSize()) ?>" width="<?php echo $this->getImageSize(); ?>" height="<?php echo $this->getImageSize(); ?>" alt="<?php echo $this->htmlEscape($item->getName()) ?>" /></a></span>
                <h5  class="j2t-product-lnk"><a href="<?php echo $item->getProductUrl() ?>"><?php echo $this->htmlEscape($item->getName()) ?></a></h5>
                </td>
            <?php $k++; endforeach;?>
                <?php if (count($items) > 1): for ($g=0; $g<($items_left-1); $g++):?>
                    <td class="j2t-upsells-list-item">&nbsp;</td>
                <?php endfor; endif;?>
                </tr>
            </table>
        </span>
        <?php endif;?>
        <?php endif;?>
    <?php endif;?>
</div>

<div id="back-ajax-add" class="back-ajax-add">
    <?php $j2t_ajax_cart_countdown = (int)Mage::getStoreConfig('j2tajaxcheckout/default/j2t_ajax_cart_countdown', Mage::app()->getStore()->getId());?>
    <?php $j2t_ajax_cart_countdown_redirection = (int)Mage::getStoreConfig('j2tajaxcheckout/default/j2t_ajax_cart_countdown_redirection', Mage::app()->getStore()->getId());?>
    <?php if ($j2t_ajax_cart_countdown > 0 && $j2t_ajax_cart_countdown_redirection == 0):?>
    <a id="j2t-continue-link" class="j2t-continue-link count-down-btn" href="javascript:void(0);" onclick="hideJ2tOverlay();"><span class="count-down-btn-inner"><?php echo $this->__('Continue shopping');?></span></a>
        <span class="j2t-or"><?php echo $this->__('or');?></span>
    <a id="j2t-checkout-link" class="j2t-checkout-link" href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('View cart & checkout');?></span></a>
    <?php elseif ($j2t_ajax_cart_countdown > 0 && $j2t_ajax_cart_countdown_redirection > 0):?>
    <a id="j2t-continue-link" class="j2t-continue-link" href="javascript:void(0);" onclick="hideJ2tOverlay();"><span><?php echo $this->__('Continue shopping');?></span></a>
        <span class="j2t-or"><?php echo $this->__('or');?></span>
    <a id="j2t-checkout-link" class="j2t-checkout-link count-down-btn" href="<?php echo $this->getUrl('checkout/cart'); ?>"><span class="count-down-btn-inner"><?php echo $this->__('View cart & checkout');?></span></a>
    <?php else:?>
    <a id="j2t-continue-link" class="j2t-continue-link" href="javascript:void(0);" onclick="hideJ2tOverlay();"><span><?php echo $this->__('Continue shopping');?></span></a>
        <span class="j2t-or"><?php echo $this->__('or');?></span>
    <a id="j2t-checkout-link" class="j2t-checkout-link" href="<?php echo $this->getUrl('checkout/cart'); ?>"><span><?php echo $this->__('View cart & checkout');?></span></a>
    <?php endif;?>
</div>

<div id="cart_content" class="cart_content"><?php
echo $this->j2tAddCartLink();
?></div>
<div class="cart_side_ajax">
    <?php echo $this->getChildHtml('cart_sidebar_ajax') ?>
</div>
<div class="j2t_ajax_message">
    <?php //echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <ul class="messages">
        <li class="<?php echo $this->getJ2tMessageType();?>-msg">
            <ul>
                <li>
                    <?php if ($this->getJ2tImg()):?><div class="j2tajax-checkout-img"><?php echo $this->getJ2tImg();?></div><?php endif;?>
                    <div class="j2tajax-checkout-txt"><?php echo $this->getJ2tMessage();?></div>
                </li>
            </ul>
        </li>
    </ul>
</div>

<div class="j2t_full_cart_content" id="j2t_full_cart_content">
    <?php echo $this->getChildHtml('cart_content_ajax');?>
</div>
