<?php
/**
 * J2t_Ajaxcheckout
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@j2t-design.com so we can send you a copy immediately.
 *
 * @category   Magento extension
 * @package    J2t_Ajaxcheckout
 * @copyright  Copyright (c) 2012 J2T DESIGN. (http://www.j2t-design.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
    $_productCollection=$this->getLoadedProductCollection();
    $_helper = $this->helper('catalog/output');
    $cpt = 0;
    $cpt2 = 0;
    $array_restrictions = explode(',',preg_replace('/\s+/', '', Mage::getStoreConfig('j2tajaxcheckout/default/j2t_ajax_cart_options_restrictions', Mage::app()->getStore()->getId())));
    $urls = array();
    $keys = array();
?>

<script type="text/javascript">
<?php if($_productCollection->count()): ?>
    //var ajax_cart_keys = Array(<?php echo $_productCollection->count(); ?>);
    <?php 
    foreach ($_productCollection as $_product): 
        $product_url = str_replace("options=cart", "", $this->getAddToCartUrl($_product)); //->getProductUrl();
        if (in_array($_product->getId(), $array_restrictions)){
            $urls[] = "ajax_products_urls[$cpt] = '$product_url'";
            $cpt++;
        }
        $keys[] =  array("product_url" => $_product->getProductUrl(), "product_type" => $_product->getTypeId(), "url_key" => $_product->getUrlKey(), "product_url_cart" => $this->getAddToCartUrl($_product), "product_id" => $_product->getId());
        $cpt2++;
    endforeach; 
    ?>
    var ajax_products_keys = <?php echo Zend_Json::encode($keys); ?>;
    <?php
    if (sizeof($urls)){
    ?>
        var ajax_products_urls = Array(<?php echo sizeof($urls); ?>);
        <?php echo implode(';', $urls);?>;
        <?php //echo implode(';', $keys);?>;
    <?php
    }
    ?>
    
        
<?php endif; ?>

</script>